### ISSUE TITLE
Chess logos for Shallow Blue

### ISSUE THREAD

**Issue by ChessGUI** [GunshipPenguin/shallow-blue#14]
![shallow blue 1](https://user-images.githubusercontent.com/2707025/28237902-294d69f2-6949-11e7-8714-7fe7dd6a1801.jpg)
![shallow blue 2](https://user-images.githubusercontent.com/2707025/28237903-2dac0ada-6949-11e7-9b88-58b111354478.jpg)
![shallow blue 3](https://user-images.githubusercontent.com/2707025/28237905-33d44508-6949-11e7-80e7-d0b65c7200e4.jpg)
![shallow blue 4](https://user-images.githubusercontent.com/2707025/28237907-37eeb5e2-6949-11e7-8bad-27cb915d0733.jpg)
![shallow blue 5](https://user-images.githubusercontent.com/2707025/28237908-3b24dc1e-6949-11e7-97de-b6e8e2d16dee.jpg)
![shallow blue 6](https://user-images.githubusercontent.com/2707025/28237911-3fd586fa-6949-11e7-889f-dc62509343f0.jpg)
cf. uploaded chess logos for Shallow Blue ;
I suggest to download the freeware **Photofiltre** http://photofiltre.free.fr/ -and you can easily convert the format into Bitmap and a maximum size of 100x50 that can be used with **Arena/ChessGUI/WinBoard or ChessBase (Fritz-Interface)**

**Comment by GunshipPenguin** [comment]
de95453ab94192110a6f5ae6da9e17050840ea8e Adds a logo
b89d843d618fcf6e44c174e6cf4ca9b70c289f02 Adds a landscape logo mockup that I was able to import into arena with no problems
