### ISSUE TITLE
both 1.02 executables crash on Windows 7 SP1 64 bit

### ISSUE THREAD

**Issue by yellow-panther** [GunshipPenguin/shallow-blue#15]
Hello,

are these builts made for Haswell-computers too (.BMI2 executables)? Cannot run both 1.0.2 versions on my pc with  ivy-bridge-microarchitecture.

**Comment by rwbc** [comment]
Same here.

**Comment by GunshipPenguin** [comment]
Hi there,

The builds should work fine on Haswell machines. Did you verify that the SHA256 sums match those on the releases page?

Also:
- What error message are you getting (if any)?
- What version of Windows are you using?
- What specific model of CPU are you using?

**Comment by rwbc** [comment]
Hi Rhys,

I replied more to the header of the first post.
My OS is WIN 7 64 bit as the OPs system, but I don't have Haswell here.
Actually it is an old quadcore (i2) without popcount, but version 1.01 nevertheless
was running here.

Guenther

**Comment by GunshipPenguin** [comment]
@rwbc @yellow-panther I believe I've found the problem. 

It seems I accidentally compiled the two 1.0.2 windows binaries for my laptop's architecture (broadwell) instead of only using -mtune=generic.

I've uploaded new windows binaries to the 1.0.2 release, can you tell me if they work for you.

**Comment by rwbc** [comment]
Both work now! Thanks.

Guenther

**Comment by GunshipPenguin** [comment]
Awesome! I'm going to close this then. Open a new issue if you have any more problems.
